server:
  port: 7004

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8001/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:frogtech
    username: hr
    password: hr
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 1532
  sleuth:
    sampler:
      percentage: 1
#Http收集
  zipkin:
    base-url: http://localhost:9411



info:
  app:
    name: eureka-client1
management:
  security:
    enabled: false

hello:
  name: lisi




