server:
  port: 7003
  context-path: /client


eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8001/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    home-page-url-path: /client
    metadata-map:
      management.port: 8061
spring:
  application:
    name: eureka-client2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:frogtech
    username: hr
    password: hr

feign:
  hystrix:
    enabled: true

info:
  app:
    name: eureka-client2
management:
  port: 8061  #
