server:
  port: 7003
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8001/eureka,http://eureka2.com:8002/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: eureka-client2

feign:
  hystrix:
    enabled: true

info:
  app:
    name: eureka-client2
