server:
  port: 7003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: eureka-client2

info:
  app:
    name: eureka-client2
