server:
  port: 9411
spring:
  application:
    name: zipkin-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useSSL=true
    username: root
    password: root
    continue-on-error: true
    initialize: true
    schema: classpath:/mysql.sql
#切换存储过程
zipkin:
  storage:
    type: mysql