spring:
  application:
    name: rabbitmq-hello
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 1532
    #publisher-confirms: true
    #virtual-host: /
server:
  port: 8888