server:
  port: 7006
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: client-feign
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:frogtech
    username: hr
    password: hr
