server:
  port: 7006
eureka:
  client:
    service-url:
      defaultZone: http://user:password@eureka1.com:8001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: client-feign
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:frogtech
    username: hr
    password: hr
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka-client1: #！！！！！！！！！此处服务名必须要与@FeignClient()注解中指定的服务名大小写一致
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ReadTimeout: 2000
    ConnectTimeout: 500
    OkToRetryOnAllOperations: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.daishuai.springcloud.service.DeptService: debug

