spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daishuai/springcloud-properties.git

server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8001/eureka

